# importing the module
from youtube_transcript_api import YouTubeTranscriptApi
import re

# retrieve the available transcripts

id = input('Video ID: ')

transcript_list = YouTubeTranscriptApi.list_transcripts(id)

# iterate over all available transcripts

f = open("captions.htm", "w", encoding="utf-8")

for transcript in transcript_list:

    lines = transcript.fetch()

    text = ''
    for line in lines:
        line = str(line)
        if re.search('^[0-9]+$', line) is None and re.search('^[0-9]{2}:[0-9]{2}:[0-9]{2}', line) is None and re.search('^$', line) is None:
            ls = line.split("'")
            #text += ls[3] + ','
            text = ls[3] + '\n'
            
            f.write(text)



#print(text)



f.close()

exit()

    

	# the Transcript object provides metadata
	# properties
##	print(
##		transcript.video_id,
##		transcript.language,
##		transcript.language_code,
##	
##		# whether it has been manually created or
##		# generated by YouTube
##		transcript.is_generated,
##		
##		# whether this transcript can be translated 
##		# or not
##		transcript.is_translatable,
##		
##		# a list of languages the transcript can be 
##		# translated to
##		transcript.translation_languages,
##	)

##	exit()
##
##	lc = input('Language code:')
##
##	# translating the transcript will return another
##	# transcript object
##	print(transcript.translate('zh-hk').fetch())

lc = input('Language code:')

# you can also directly filter for the language you are
# looking for, using the transcript list
transcript = transcript_list.find_transcript([lc])

# or just filter for manually created transcripts
transcript = transcript_list.find_manually_created_transcript([lc])
